Develop/scripts-foundation.js, Develop/style.css, index.html
Added a responsive top nav, and fixed issue where the rest of the site did not show up on mobile.
=> Responsive fix

Assets/id-notes.md, Develop/style.css, index.html
I changed the top nav bar to add remove the searchbar & add a dropdown with scrollwheel for selecting states.
=> More index changes

Develop/script-ls.js, index.html
added data state abbreviations to index.html. updated luke js file with covid tracking project api example
=> index.html data abbreviations. covid tracking project api

index.html
Added classes to Dropdown menu items, started working on stats cards.
=> Index changes2

Develop/script-ls.js
Added on click event for state dropdown menu selection. on click event gets daily values from covid tracker api and returns variables
=> updated covid tracking api luke js file

Develop/script-ls.js
Added variable comments for current day covid tracking api
=> Add luke js file

Assets/id-notes.md, index.html
Changed IDs based on COVID stats API variables.
=> Index changes3

Develop/style.css, index.html
Some styling changes, working on responsiveness.
=> Index changes4

Develop/maptest.js
Deleted console.log on maptest.js
=> edit maptest.js file

Assets/usmap/landing.html
=> adding landing file

README.md
Put team names into a chart & added a link to the deployed project.
=> Readme change2

Develop/style.css, index.html
Updating the navbar to have the same background color and changed font to bold and black. It also changed the other links to black text (ex. link to cdc) when I did this, but when you hover it's still blue on the links. Not sure if this is ok?  I wasn't able to change the litte triangle on the right of "states" to be black. Looks like that may be a sass thing.
=>  updating navbar

Develop/style.css
Added a margin in css so that the shadow from one box wouldn't overlap another section.
=> added a margin in css

Assets/usmap/index.html, Assets/usmap/mapdata.js, index.html
Moved new index.html to root folder.
=> Landing page2

Assets/usmap/mapdata.js
Clicking from the landing page now works! Opens up the dashboard with the correct data.
=> Landing Page links

Assets/usmap/mapdata.js, dashboard.html, index.html
Updated landing page layout to fit Foundation, changed map id to `#landing-map` to fend off conflicts with the dashboard map.
=> Landing page now in Foundation XY Grid

Assets/id-notes.md, Develop/alertbar.js, Develop/style.css, dashboard.html
Alert Bar Buttons now link to a google search for that topic in that state.
=> Alert bar update

Assets/id-notes.md, Develop/script-ls.js, dashboard.html
Moved Chart above map, worked on mobile style.
=> Chart div update

Develop/maptest.js
update the map to center at each state when drop down button is clicked
=> update maptest.js with new code

Develop/style.css, dashboard.html
I fixed the background in the navbar on the right on the dashboard page to match the rest, and fixed the font on the index page.  I added some screen reader text for the map and chart area so when the user goes over the area it will say that there is a map or chart there. I also added to the empty link at the bottom a link to disaster financial assistance for people struggling right now. Not sure if you guys think this is good to add?
=> updating dashboard and css.

Develop/script-ls.js, dashboard.html
Changed chart data to show daily positive cases rather than percentage of daily positive cases per daily tests administered. Changed chart tooltip pop up contents. Added abbreviation definitions to p tag within chart div in dashboard.html
=> Changed chart data, tooltip, legend

Assets/usmap/mapscript.js, index.html
Screenreader links on index.html now work as intended (push abbreviation to localStorage & open dashboard.html).
=> Screen Reader Index Update

Develop/script-ls.js, dashboard.html
I added toLocaleString() & .lead class to each statistic, to make them more legible.
=> Stat Display Update

dashboard.html
Updating for the screenreader capabilities on dashboard. Was not able to hide the map.
=> updating dashboard for screenreader

Develop/style.css, dashboard.html
Added a title for the chart legend, and made the text gray (more unobtrusive).
=> Chart legend

dashboard.html
Added an accessible nav bar, return to top button, and skip link for maps area.
=> Screenreader updates
